//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SunShine_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int BillingID { get; set; }
        public int GuestIDFK { get; set; }
        public Nullable<decimal> BarCharge { get; set; }
        public Nullable<decimal> TeleChrage { get; set; }
        public Nullable<decimal> RoomCharge { get; set; }
        public Nullable<decimal> WiFiCharges { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
